### ISSUE TITLE
Secrets from env

### ISSUE THREAD

**Issue by shyim** [shyim/tanjun#6]
We should support things like:

```yaml
secrets:
  from_env:
    - MY_ENV
```

We load then the currently populated environment variables as secrets. In that way we can grab secrets set in GitHub Actions and use them for deployments

**Comment by shyim** [comment]
```
  secrets:
    from_env:
      FOO: ~
    from_env_file:
      - .env.test
```

this works now
