### ISSUE TITLE
Add 1password integration

### ISSUE THREAD

**Issue by shyim** [shyim/tanjun#9]
```yaml
secrets:
  1password:
    ref: 'op://my-vault/item'
```

It reads the vault item and gets the secrets from there
